### ISSUE TITLE
Plans idea

### ISSUE THREAD

**Issue by sils** [hemangsk/viperdev-site#22]
For the plans, can we have an extra field for location and duration and price range?

**Comment by hemangsk** [comment]
I think we can also add sth like labels for these fields so that its more clear as to what means what. 
So it can go like `Location` then Location Name, `Duration` then Time etc. 

![screen shot 2016-12-27 at 4 41 04 pm](https://cloud.githubusercontent.com/assets/13018570/21498531/4bd9e3bc-cc53-11e6-89ef-c8377e58d229.png)

**Comment by hemangsk** [comment]
Or more like this one, without labels
![screen shot 2016-12-27 at 4 35 32 pm](https://cloud.githubusercontent.com/assets/13018570/21498598/fcb97e18-cc53-11e6-9992-48700728263c.png)

**Comment by sils** [comment]
I like the second one ideally with arbitrary number of fields (which don't
have a label then). Also add a subtitle?

**Comment by hemangsk** [comment]
![screen shot 2016-12-27 at 5 01 29 pm](https://cloud.githubusercontent.com/assets/13018570/21498825/312b4116-cc56-11e6-82dc-f178afbab5e0.png)

**Comment by sils** [comment]
Like it

**Comment by sils** [comment]
Maybe make the subtitle into the same field as the title but with a slim
font

**Comment by hemangsk** [comment]
Done 👍  😃 
![screen shot 2016-12-27 at 9 05 28 pm](https://cloud.githubusercontent.com/assets/13018570/21502811/8de38d92-cc78-11e6-8194-7b2034094d73.png)
